using System;
using System.Collections.Generic;
using System.IO;

namespace splitDecomp
{
    partial class Program
    {
        static string[] SonicActions =
        {
            "action_s_s0064_sonic",
            "action_s_s0065_sonic",
            "action_s_s0066_sonic",
            "action_s_s0089_sonic",
            "action_s_s0029_sonic",
            "action_s_s0013_sonic",
            "action_s_s0031_sonic",
            "action_s_s0032_sonic",
            "action_s_s0033_sonic",
            "action_s_s0022_sonic",
            "action_s_s0004_sonic",
            "action_s_s0006_sonic",
            "action_s_s0009_sonic",
            "action_s_s0038_sonic",
            "action_s_s0042_sonic",
            "action_s_s0044_sonic",
            "action_s_s0045_sonic",
            "action_s_s0015_sonic",
            "action_s_s0016_sonic",
            "action_s_s0050_sonic",
            "action_s_s0051_sonic",
            "action_s_s0052_sonic",
            "action_s_s0002_sonic",
            "action_s_s0046_sonic",
            "action_s_s9000_sonic",
            "action_s_s9001_sonic",
            "action_s_s0028_sonic",
            "action_s_s0024_sonic",
            "action_s_s0025_sonic",
            "action_s_s0026_sonic",
            "action_s_s0027_sonic",
            "action_s_s0001_sonic",
            "action_s_s0017_sonic",
            "action_s_s0037_sonic",
            "action_s_s0058_sonic",
            "action_s_s0005_sonic",
            "action_s_s0007_sonic",
            "action_s_s0012_sonic",
            "action_s_s0067_sonic",
            "action_s_s0019_sonic",
            "action_s_s0020_sonic",
            "action_s_s0021_sonic",
            "action_s_s0030_sonic",
            "action_s_s0011_sonic",
            "action_s_s0018_sonic",
            "action_s_s0068_sonic",
            "action_s_s0070_sonic",
            "action_s_s0071_sonic",
            "action_s_s0035_sonic",
            "action_s_s0036_sonic",
            "action_s_s0054_sonic",
            "action_s_s0057_sonic",
            "action_s_s0055_sonic",
            "action_s_s0056_sonic",
            "action_s_s0069_sonic",
            "action_s_s0076_sonic",
            "action_s_s0034_sonic",
            "action_s_s0059_sonic",
            "action_s_s0060_sonic",
            "action_s_s0061_sonic",
            "action_s_s0062_sonic",
            "action_s_s0003_sonic",
            "action_s_s0043_sonic",
            "action_s_s0049_sonic",
            "action_s_s0077_sonic",
            "action_s_s0072_sonic",
            "action_s_s0073_sonic",
            "action_s_s0080_sonic",
            "action_s_s0081_sonic",
            "action_s_s0082_sonic",
            "action_s_item_r0",
            "action_s_item_r1",
            "action_s_item_r2",
            "action_s_item_s0",
            "action_s_item_s1",
            "action_s_item_s2",
            "action_s_item_l0",
            "action_s_item_l1",
            "action_s_item_l2",
            "action_s_s0053_sonic",
            "action_s_last",
        };

        static string[] TailsActions = 
        {
            "action_m_m0104_miles",
            "action_m_m0001_miles",
            "action_m_m0136_miles",
            "action_m_m0137_miles",
            "action_m_m0138_miles",
            "action_m_m0112_miles",
            "action_m_m9006_miles",
            "action_m_m0150_miles",
            "action_m_m9014_miles",
            "action_m_m0108_miles",
            "action_m_m0109_miles",
            "action_m_m0110_miles",
            "action_m_m0111_miles",
            "action_m_m0130_miles",
            "action_m_m0131_miles",
            "action_m_m0119_miles",
            "action_m_m0120_miles",
            "action_m_m0105_miles",
            "action_m_m9001_miles",
            "action_m_m9002_miles",
            "action_m_m0103_miles",
            "action_m_m9010_miles",
            "action_m_m9011_miles",
            "action_m_m9012_miles",
            "action_m_m0121_miles",
            "action_m_m0122_miles",
            "action_m_m0123_miles",
            "action_m_m0128_miles",
            "action_m_m0129_miles",
            "action_m_m0124_miles",
            "action_m_m0125_miles",
            "action_m_m0126_miles",
            "action_m_m0127_miles",
            "action_m_m0113_miles",
            "action_m_m0114_miles",
            "action_m_m0115_miles",
            "action_m_m0116_miles",
            "action_m_m0117_miles",
            "action_m_m9004_miles",
            "action_m_m9005_miles",
            "action_m_m9007_miles",
            "action_m_m0139_miles",
            "action_m_m0140_miles",
            "action_m_m0141_miles",
            "action_m_m9000_miles",
            "action_m_m0142_miles",
            "action_m_m0101_miles",
            "action_m_m0149_miles",
            "action_m_m0151_miles",
            "action_m_m0152_miles",
            "action_m_m9015_miles",
            "action_m_m9016_miles",
            "action_m_m9017_miles",
            "action_m_m9018_miles",
            "action_m_item_s0",
            "action_m_item_s1",
            "action_m_item_s2",
            "action_m_item_b0",
            "action_m_item_b1",
            "action_m_item_b2",
            "action_m_m0106_miles",
            "action_m_m0118_miles",
            "action_m_cart0",
            "action_m_last",
            "action_m_m0002_miles",
        };

        static string[] KnucklesActions =
        {
            "action_k_k0033_knuckles",
            "action_k_k0038_knuckles",
            "action_k_k0039_knuckles",
            "action_k_k0034_knuckles",
            "action_k_k0035_knuckles",
            "action_k_k0005_knuckles",
            "action_k_k0012_knuckles",
            "action_k_k0013_knuckles",
            "action_k_k0002_knuckles",
            "action_k_k0014_knuckles",
            "action_k_k0015_knuckles",
            "action_k_k0016_knuckles",
            "action_k_k0023_knuckles",
            "action_k_k0024_knuckles",
            "action_k_k0003_knuckles",
            "action_k_k0004_knuckles",
            "action_k_k0019_knuckles",
            "action_k_k0001_knuckles",
            "action_k_k0006_knuckles",
            "action_k_k0009_knuckles",
            "action_k_k0017_knuckles",
            "action_k_k0010_knuckles",
            "action_k_k0011_knuckles",
            "action_k_k0018_knuckles",
            "action_k_k0007_knuckles",
            "action_k_k0008_knuckles",
            "action_k_k0022_knuckles",
            "action_k_k0025_knuckles",
            "action_k_k0026_knuckles",
            "action_k_k0027_knuckles",
            "action_k_k0028_knuckles",
            "action_k_k0030_knuckles",
            "action_k_k0031_knuckles",
            "action_k_k0032_knuckles",
            "action_k_patya_talk1_patya",
            "action_k_k0029_knuckles",
            "action_k_cart0",
            "action_k_last",
        };

        static string[] AmyActions = 
        {
            "action_a_a0006_amy",
            "action_a_a0010_amy",
            "action_a_a0015_amy",
            "action_a_a0121_amy",
            "action_a_a0001_amy",
            "action_a_a0005_amy",
            "action_a_a0007_amy",
            "action_a_a0008_amy",
            "action_a_a0011_amy",
            "action_a_a0124_amy",
            "action_a_a0126_amy",
            "action_a_a0002_amy",
            "action_a_a0003_amy",
            "action_a_a0004_amy",
            "action_a_a0120_amy",
            "action_a_a0099_amy",
            "action_a_a0100_amy",
            "action_a_a0101_amy",
            "action_a_a0102_amy",
            "action_a_a0103_amy",
            "action_a_a0104_amy",
            "action_a_a0105_amy",
            "action_a_a0106_amy",
            "action_a_a0107_amy",
            "action_a_a0108_amy",
            "action_a_a0109_amy",
            "action_a_a0110_amy",
            "action_a_a0111_amy",
            "action_a_a0112_amy",
            "action_a_a0113_amy",
            "action_a_a0123_amy",
            "action_a_a0125_amy",
            "action_a_a0127_amy",
            "action_a_a0128_amy",
            "action_a_a0129_amy",
            "action_a_a0131_amy",
            "action_a_a0815_amy",
            "action_a_a0133_amy",
            "action_a_a0134_amy",
            "action_a_a0135_amy",
            "action_a_a0136_amy",
            "action_a_a0137_amy",
            "action_a_a0114_amy",
            "action_a_a0115_amy",
            "action_a_a0117_amy",
            "action_a_a0118_amy",
            "action_a_a0119_amy",
            "action_a_a0814_amy",
            "action_a_a0835_amy",
            "action_a_a0827_amy",
            "action_a_a0828_amy",
            "action_a_a0829_amy",
            "action_a_a0830_amy",
            "action_a_a0831_amy",
            "action_a_a0832_amy",
            "action_a_a0833_amy",
            "action_a_a0836_amy",
            "action_a_a0837_amy",
            "action_a_a0800_amy",
            "action_a_a0818_amy",
            "action_a_a0803_amy",
            "action_a_a0804_amy",
            "action_a_a0805_amy",
            "action_a_a0817_amy",
            "action_a_a0819_amy",
            "action_a_a0820_amy",
            "action_a_a0822_amy",
            "action_a_a0823_amy",
            "action_a_a0824_amy",
            "action_a_a0825_amy",
            "action_a_a0826_amy",
            "action_a_a0838_amy",
            "action_a_a0839_amy",
            "action_a_a0840_amy",
            "action_a_a0841_amy",
            "action_a_a0843_amy",
            "action_a_a0844_amy",
            "action_a_a0845_amy",
            "action_a_a0846_amy",
            "action_a_a0847_amy",
            "action_a_item_hm0",
            "action_a_item_hm1",
            "action_a_item_hm2",
            "action_a_item_ha0",
            "action_a_item_ha1",
            "action_a_item_ha2",
            "action_a_cart0",
            "action_a_last",
            "action_a_a0014_amy",
        };

        static string[] BigActions = 
        {
            "action_b_b0012_big",
            "action_b_b0013_big",
            "action_b_b0014_big",
            "action_b_b0003_big",
            "action_b_b0004_big",
            "action_b_b0010_big",
            "action_b_b0001_big",
            "action_b_b0002_big",
            "action_b_b0011_big",
            "action_b_b0027_big",
            "action_b_b0028_big",
            "action_b_b0029_big",
            "action_b_b0030_big",
            "action_b_b0031_big",
            "action_b_b0006_big",
            "action_b_b0007_big",
            "action_b_b0020_big",
            "action_b_b0042_big",
            "action_b_b0036_big",
            "action_b_b0037_big",
            "action_b_b0022_big",
            "action_b_b0034_big",
            "action_b_b0035_big",
            "action_b_b0032_big",
            "action_b_b0033_big",
            "action_b_b0038_big",
            "action_b_b0039_big",
            "action_b_b0040_big",
            "action_b_b0041_big",
            "action_b_item_s0",
            "action_b_item_s1",
            "action_b_item_s2",
            "action_b_item_u0",
            "action_b_item_u1",
            "action_b_item_u2",
            "action_b_cart0",
            "action_b_last",
        };

        static string[] GammaActions = {
            "action_e_e0002_e102",
            "action_e_e0003_e102",
            "action_e_e0004_e102",
            "action_e_e0005_e102",
            "action_e_e0001_e102",
            "action_e_e0006_e102",
            "action_e_e0024_e102",
            "action_e_e0025_e102",
            "action_e_e0019_e102",
            "action_e_e0033_e102",
            "action_e_e0015_e102",
            "action_e_e0018_e102",
            "action_e_e0034_e102",
            "action_e_e0035_e102",
            "action_e_e0007_e102",
            "action_e_e0009_e102",
            "action_e_e0010_e102",
            "action_e_e0011_e102",
            "action_e_e0016_e102",
            "action_e_e0020_e102",
            "action_e_e0037_e102",
            "action_e_e0038_e102",
            "action_e_e0039_e102",
            "action_e_e0040_e102",
            "action_e_e0041_e102",
            "action_e_e0042_e102",
            "action_e_e0043_e102",
            "action_e_e0044_e102",
            "action_e_e0026_e102",
            "action_e_e0027_e102",
            "action_e_e0036_e102",
            "action_e_cart0",
            "action_e_last",
            "action_e_lastkamae",
        };

        static Dictionary<string, string> ActionsWithObjectsInDLLs = new Dictionary<string, string>()
        {
            { "action_al_e0001_al_model", "___ADV03_OBJECTS[1]" },
            { "action_al_e0008_al_model", "___ADV03_OBJECTS[1]" },
            { "action_al_e0009_al_model", "___ADV03_OBJECTS[1]" },
            { "action_al_walk_al_model", "___ADV03_OBJECTS[1]" },
            { "action_al_stand_al_model", "___ADV03_OBJECTS[1]" },
            { "action_al_sing_al_model", "___ADV03_OBJECTS[1]" },
            { "action_al_damage_al_model", "___ADV03_OBJECTS[1]" },
            { "action_al_damage2_al_model", "___ADV03_OBJECTS[1]" },
            { "action_al_e0002_al_model", "___ADV03_OBJECTS[1]" },
            { "action_al_e0003_al_model", "___ADV03_OBJECTS[1]" },
            { "action_p_p0001_patya", "___ADV03_OBJECTS[7]" },
            { "action_p_p0003_patya", "___ADV03_OBJECTS[7]" },
            { "action_p_p0002_patya", "___ADV03_OBJECTS[7]" },
            { "action_p_p0004_patya", "___ADV03_OBJECTS[7]" },
            { "action_p_p0005_patya", "___ADV03_OBJECTS[7]" },
            { "action_kz_0003_k_normal", "___ADV03_OBJECTS[6]" },
        };

        // Fill the list of actions that have objects in DLLs 
        static void InitDLLActionList()
        {
            foreach (string action in SonicActions)
            {
                ActionsWithObjectsInDLLs.Add(action, "___SONIC_OBJECTS[0]");
            }
            foreach (string action in TailsActions)
            {
                ActionsWithObjectsInDLLs.Add(action, "___MILES_OBJECTS[0]");
            }
            foreach (string action in KnucklesActions)
            {
                ActionsWithObjectsInDLLs.Add(action, "___KNUCKLES_OBJECTS[0]");
            }
            foreach (string action in AmyActions)
            {
                ActionsWithObjectsInDLLs.Add(action, "___AMY_OBJECTS[0]");
            }
            foreach (string action in BigActions)
            {
                ActionsWithObjectsInDLLs.Add(action, "___BIG_OBJECTS[0]");
            }
            foreach (string action in GammaActions)
            {
                ActionsWithObjectsInDLLs.Add(action, "___E102_OBJECTS[0]");
            }
        }

        // Quick stub for action generation
        static void ActionToNJAfromText(string actionName, string objectName, string motionName, TextWriter writer)
        {
            writer.WriteLine(Environment.NewLine + "ACTION {0}[]", actionName);
            writer.WriteLine("START");
            writer.WriteLine("ObjectHead      {0},", objectName);
            writer.WriteLine("Motion          " + motionName);
            writer.Write("END");
        }
        /*
        // This is probably not going to be used, but just in case here's a list of actions whose object is in the EXE but the motion is in a DLL
        Dictionary<string, string> ActionsWithMotionsFromDLL = new Dictionary<string, string>()
        {
            { "action_e101_jump0", "___E102_MOTIONS[0]" },
            { "action_e101_jump2", "___E102_MOTIONS[2]" },
            { "action_e101_jump3", "___E102_MOTIONS[3]" },
            { "action_e104_jump0", "___E102_MOTIONS[0]" },
            { "action_e104_jump2", "___E102_MOTIONS[2]" },
            { "action_e104_jump3", "___E102_MOTIONS[3]" },
            { "action_e103_jump0", "___E102_MOTIONS[0]" },
            { "action_e103_jump2", "___E102_MOTIONS[2]" },
            { "action_e103_jump3", "___E102_MOTIONS[3]" },
        };
        */
    }
}