version: '{build}'
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform:
- x64
- x86
install:
- cmd: >-
   
    cd %APPVEYOR_BUILD_FOLDER%
    
    git submodule update --init --recursive
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  project: sa_tools_research.sln
after_build:
- cmd: >-
   
    cd C:\projects\sa-tools-research\build\
    
    7z a "C:\projects\sa-tools-research\SAToolsResearch %PLATFORM%.7z" *
artifacts:
- path: SAToolsResearch $(platform).7z
  name: satoolsresearch

deploy:
- provider: GitHub
  auth_token:
    secure: WwdJ8DbEJO7DM1m+oJVoa19eLcsjewV27lSUZHUHv4hTNzlJdbE9WApe8rC2elHwdtorvpKTnRrlwV+WVWmGROY8N5RatLRy/4ZK61B3bFgW/DDR5YrYnjkGiNgnOdAU
  artifact: satoolsresearch
  on:
    branch: master
